all:
  vars:
    ansible_ssh_private_key_file: ../sshkeys/iac-for-everyone
    ansible_user: root

load-balancer:
  vars:
  hosts:
    load-balancer:
      ansible_host: 134.122.113.255
      haproxy_width_stats: True
      haproxy_with_auth: False
      haproxy_user: user
      haproxy_password: password


# Nginx Servers
web-servers:
  hosts:
    nginx-01:
      ansible_host: 137.184.21.50
    nginx-02:
       ansible_host: 134.122.121.229
    # nginx-03:
    #   ansible_host: 1.1.1.1
